//HOME
const SET_VARIANTS = 'SET_VARIANTS'
const SOLVE_VARIANT = 'SOLVE_VARIANT'
const SOLVE_VARIANTS = 'SOLVE_VARIANTS'
const CLOSE_MODEL = 'CLOSE_MODEL'
const STEP_VARIANT = 'STEP_VARIANT'


export default {
  SET_VARIANTS,
  SOLVE_VARIANT,
  SOLVE_VARIANTS,
  CLOSE_MODEL,
  STEP_VARIANT
}