const SAVE_SHOPIFY_DATA = 'SAVE_SHOPIFY_DATA'
const ACTIVE_LOADING = 'ACTIVE_LOADING'
const REGISTRO_BTN_ACTIVE = 'REGISTRO_BTN_ACTIVE'


export default {
  SAVE_SHOPIFY_DATA,
  REGISTRO_BTN_ACTIVE,
  ACTIVE_LOADING
}